import mongoose from 'mongoose';
import dotenv from 'dotenv';
import SupplyTransaction from '../models/SupplyTransaction.js';

dotenv.config();

// Excel data from the image description
const excelData = [
  // Maize Transactions (5 records)
  {
    transaction_date: '2025-05-01',
    state: 'Bihar',
    supplier_name: 'SHRI GANESH ENTERPRISES',
    location: 'GULABBAGH',
    warehouse_name: 'SATISH KUMAR WAREHOUSE',
    chamber_no: '16',
    commodity: 'Maize',
    variety: 'Hybrid',
    gate_pass_no: '754201',
    vehicle_no: 'BR11GD-8172',
    weight_slip_no: '1300',
    gross_weight_mt: 12.690,
    tare_weight_mt: 6.790,
    no_of_bags: 93,
    net_weight_mt: 5.900,
    rate_per_mt: 22310.00,
    gross_amount: 131629.00,
    hlw_wheat: null,
    excess_hlw: 0,
    deduction_amount_hlw: 0,
    moisture_moi: 14.80,
    excess_moisture: 0.80,
    bddi: 4.95,
    excess_bddi: 0,
    moi_bddi: 0.80,
    weight_deduction_kg: 47.20,
    deduction_amount_moi_bddi: 1053.03,
    other_deductions: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    net_amount: 130575.97,
    remarks: ''
  },
  {
    transaction_date: '2025-05-01',
    state: 'Bihar',
    supplier_name: 'SHRI GANESH ENTERPRISES',
    location: 'GULABBAGH',
    warehouse_name: 'SATISH KUMAR WAREHOUSE',
    chamber_no: '16',
    commodity: 'Maize',
    variety: 'Hybrid',
    gate_pass_no: '754202',
    vehicle_no: 'BR11GD-8173',
    weight_slip_no: '1301',
    gross_weight_mt: 12.650,
    tare_weight_mt: 6.680,
    no_of_bags: 93,
    net_weight_mt: 5.970,
    rate_per_mt: 22310.00,
    gross_amount: 133190.70,
    hlw_wheat: null,
    excess_hlw: 0,
    deduction_amount_hlw: 0,
    moisture_moi: 14.50,
    excess_moisture: 0.50,
    bddi: 4.80,
    excess_bddi: 0,
    moi_bddi: 0.50,
    weight_deduction_kg: 29.85,
    deduction_amount_moi_bddi: 665.87,
    other_deductions: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    net_amount: 132524.83,
    remarks: ''
  },
  {
    transaction_date: '2025-05-01',
    state: 'Bihar',
    supplier_name: 'SHRI GANESH ENTERPRISES',
    location: 'GULABBAGH',
    warehouse_name: 'SATISH KUMAR WAREHOUSE',
    chamber_no: '16',
    commodity: 'Maize',
    variety: 'Hybrid',
    gate_pass_no: '754203',
    vehicle_no: 'BR11GD-8174',
    weight_slip_no: '1302',
    gross_weight_mt: 12.720,
    tare_weight_mt: 6.825,
    no_of_bags: 95,
    net_weight_mt: 5.895,
    rate_per_mt: 22310.00,
    gross_amount: 131517.45,
    hlw_wheat: null,
    excess_hlw: 0,
    deduction_amount_hlw: 0,
    moisture_moi: 14.70,
    excess_moisture: 0.70,
    bddi: 5.10,
    excess_bddi: 0,
    moi_bddi: 0.70,
    weight_deduction_kg: 41.27,
    deduction_amount_moi_bddi: 920.74,
    other_deductions: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    net_amount: 130596.71,
    remarks: ''
  },
  {
    transaction_date: '2025-05-01',
    state: 'Bihar',
    supplier_name: 'SHRI GANESH ENTERPRISES',
    location: 'GULABBAGH',
    warehouse_name: 'SATISH KUMAR WAREHOUSE',
    chamber_no: '16',
    commodity: 'Maize',
    variety: 'Hybrid',
    gate_pass_no: '754204',
    vehicle_no: 'BR11GD-8175',
    weight_slip_no: '1303',
    gross_weight_mt: 12.680,
    tare_weight_mt: 6.710,
    no_of_bags: 94,
    net_weight_mt: 5.970,
    rate_per_mt: 22310.00,
    gross_amount: 133190.70,
    hlw_wheat: null,
    excess_hlw: 0,
    deduction_amount_hlw: 0,
    moisture_moi: 14.60,
    excess_moisture: 0.60,
    bddi: 4.90,
    excess_bddi: 0,
    moi_bddi: 0.60,
    weight_deduction_kg: 35.82,
    deduction_amount_moi_bddi: 799.05,
    other_deductions: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    net_amount: 132391.65,
    remarks: ''
  },
  {
    transaction_date: '2025-05-01',
    state: 'Bihar',
    supplier_name: 'SHRI GANESH ENTERPRISES',
    location: 'GULABBAGH',
    warehouse_name: 'SATISH KUMAR WAREHOUSE',
    chamber_no: '16',
    commodity: 'Maize',
    variety: 'Hybrid',
    gate_pass_no: '754205',
    vehicle_no: 'BR11GD-8176',
    weight_slip_no: '1304',
    gross_weight_mt: 12.710,
    tare_weight_mt: 6.815,
    no_of_bags: 95,
    net_weight_mt: 5.895,
    rate_per_mt: 22310.00,
    gross_amount: 131517.45,
    hlw_wheat: null,
    excess_hlw: 0,
    deduction_amount_hlw: 0,
    moisture_moi: 14.75,
    excess_moisture: 0.75,
    bddi: 5.05,
    excess_bddi: 0,
    moi_bddi: 0.75,
    weight_deduction_kg: 44.21,
    deduction_amount_moi_bddi: 986.38,
    other_deductions: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    net_amount: 130531.07,
    remarks: ''
  },
  // Wheat Transactions (5 records)
  {
    transaction_date: '2025-04-09',
    state: 'Bihar',
    supplier_name: 'FARMKEN VENTURES',
    location: 'BUXAR',
    warehouse_name: 'SIDDHASHRAM WAREHOUSE',
    chamber_no: '2',
    commodity: 'Wheat',
    variety: 'Dara',
    gate_pass_no: 'Not Available',
    vehicle_no: 'Not Available',
    weight_slip_no: 'Not Available',
    gross_weight_mt: 8.31,
    tare_weight_mt: 2.915,
    no_of_bags: 105,
    net_weight_mt: 5.395,
    rate_per_mt: 25900.00,
    gross_amount: 139730.50,
    hlw_wheat: 74.00,
    excess_hlw: 0.00,
    deduction_amount_hlw: 0.00,
    moisture_moi: 9.20,
    excess_moisture: 0.00,
    bddi: null,
    excess_bddi: 0,
    moi_bddi: 0.00,
    weight_deduction_kg: null,
    deduction_amount_moi_bddi: 0.00,
    other_deductions: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    net_amount: 139730.50,
    remarks: ''
  },
  {
    transaction_date: '2025-04-09',
    state: 'Bihar',
    supplier_name: 'Agro Valley Trading',
    location: 'Rohtas',
    warehouse_name: 'Binod Kumar Warehouse',
    chamber_no: '1',
    commodity: 'Wheat',
    variety: 'Dara',
    gate_pass_no: 'Not Available',
    vehicle_no: 'Not Available',
    weight_slip_no: 'Not Available',
    gross_weight_mt: 8.25,
    tare_weight_mt: 2.880,
    no_of_bags: 103,
    net_weight_mt: 5.370,
    rate_per_mt: 25900.00,
    gross_amount: 139083.00,
    hlw_wheat: 74.50,
    excess_hlw: 0.50,
    deduction_amount_hlw: 695.42,
    moisture_moi: 9.50,
    excess_moisture: 0.30,
    bddi: null,
    excess_bddi: 0,
    moi_bddi: 0.30,
    weight_deduction_kg: 16.11,
    deduction_amount_moi_bddi: 417.25,
    other_deductions: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    net_amount: 137970.33,
    remarks: ''
  },
  {
    transaction_date: '2025-04-09',
    state: 'Bihar',
    supplier_name: 'FARMKEN VENTURES',
    location: 'BUXAR',
    warehouse_name: 'SIDDHASHRAM WAREHOUSE',
    chamber_no: '2',
    commodity: 'Wheat',
    variety: 'Dara',
    gate_pass_no: 'Not Available',
    vehicle_no: 'Not Available',
    weight_slip_no: 'Not Available',
    gross_weight_mt: 8.28,
    tare_weight_mt: 2.910,
    no_of_bags: 104,
    net_weight_mt: 5.370,
    rate_per_mt: 25900.00,
    gross_amount: 139083.00,
    hlw_wheat: 73.80,
    excess_hlw: 0.00,
    deduction_amount_hlw: 0.00,
    moisture_moi: 9.10,
    excess_moisture: 0.00,
    bddi: null,
    excess_bddi: 0,
    moi_bddi: 0.00,
    weight_deduction_kg: null,
    deduction_amount_moi_bddi: 0.00,
    other_deductions: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    net_amount: 139083.00,
    remarks: ''
  },
  {
    transaction_date: '2025-04-09',
    state: 'Bihar',
    supplier_name: 'Agro Valley Trading',
    location: 'Rohtas',
    warehouse_name: 'Binod Kumar Warehouse',
    chamber_no: '1',
    commodity: 'Wheat',
    variety: 'Dara',
    gate_pass_no: 'Not Available',
    vehicle_no: 'Not Available',
    weight_slip_no: 'Not Available',
    gross_weight_mt: 8.22,
    tare_weight_mt: 2.850,
    no_of_bags: 102,
    net_weight_mt: 5.370,
    rate_per_mt: 25900.00,
    gross_amount: 139083.00,
    hlw_wheat: 74.20,
    excess_hlw: 0.20,
    deduction_amount_hlw: 278.17,
    moisture_moi: 9.30,
    excess_moisture: 0.10,
    bddi: null,
    excess_bddi: 0,
    moi_bddi: 0.10,
    weight_deduction_kg: 5.37,
    deduction_amount_moi_bddi: 139.08,
    other_deductions: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    net_amount: 138665.75,
    remarks: ''
  },
  {
    transaction_date: '2025-04-09',
    state: 'Bihar',
    supplier_name: 'FARMKEN VENTURES',
    location: 'BUXAR',
    warehouse_name: 'SIDDHASHRAM WAREHOUSE',
    chamber_no: '2',
    commodity: 'Wheat',
    variety: 'Dara',
    gate_pass_no: 'Not Available',
    vehicle_no: 'Not Available',
    weight_slip_no: 'Not Available',
    gross_weight_mt: 8.35,
    tare_weight_mt: 2.930,
    no_of_bags: 106,
    net_weight_mt: 5.420,
    rate_per_mt: 25900.00,
    gross_amount: 140378.00,
    hlw_wheat: 74.30,
    excess_hlw: 0.30,
    deduction_amount_hlw: 421.13,
    moisture_moi: 9.40,
    excess_moisture: 0.20,
    bddi: null,
    excess_bddi: 0,
    moi_bddi: 0.20,
    weight_deduction_kg: 10.84,
    deduction_amount_moi_bddi: 280.76,
    other_deductions: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    net_amount: 139676.11,
    remarks: ''
  },
  // Paddy Transactions (7 records)
  {
    transaction_date: '2024-12-15',
    state: 'Bihar',
    supplier_name: 'RUDRA ENTERPRISES',
    location: 'GULABBAGH',
    warehouse_name: 'SATISH KUMAR WAREHOUSE',
    chamber_no: '16',
    commodity: 'Paddy',
    variety: 'Katarni',
    gate_pass_no: 'Not Available',
    vehicle_no: 'AF 85810',
    weight_slip_no: 'Not Available',
    gross_weight_mt: null,
    tare_weight_mt: null,
    no_of_bags: 129,
    net_weight_mt: 5.395,
    rate_per_mt: 24050.00,
    gross_amount: 129749.75,
    hlw_wheat: null,
    excess_hlw: 0,
    deduction_amount_hlw: 0,
    moisture_moi: 15.60,
    excess_moisture: 1.60,
    bddi: null,
    excess_bddi: 0,
    moi_bddi: 1.60,
    weight_deduction_kg: 86.32,
    deduction_amount_moi_bddi: 2075.60,
    other_deductions: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    net_amount: 127674.15,
    remarks: ''
  },
  {
    transaction_date: '2024-12-15',
    state: 'Bihar',
    supplier_name: 'RUDRA ENTERPRISES',
    location: 'GULABBAGH',
    warehouse_name: 'SATISH KUMAR WAREHOUSE',
    chamber_no: '16',
    commodity: 'Paddy',
    variety: 'Katarni',
    gate_pass_no: 'Not Available',
    vehicle_no: 'AF 85811',
    weight_slip_no: 'Not Available',
    gross_weight_mt: null,
    tare_weight_mt: null,
    no_of_bags: 128,
    net_weight_mt: 5.350,
    rate_per_mt: 24050.00,
    gross_amount: 128667.50,
    hlw_wheat: null,
    excess_hlw: 0,
    deduction_amount_hlw: 0,
    moisture_moi: 15.40,
    excess_moisture: 1.40,
    bddi: null,
    excess_bddi: 0,
    moi_bddi: 1.40,
    weight_deduction_kg: 74.90,
    deduction_amount_moi_bddi: 1801.35,
    other_deductions: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    net_amount: 126866.15,
    remarks: ''
  },
  {
    transaction_date: '2024-12-15',
    state: 'Bihar',
    supplier_name: 'RUDRA ENTERPRISES',
    location: 'GULABBAGH',
    warehouse_name: 'SATISH KUMAR WAREHOUSE',
    chamber_no: '16',
    commodity: 'Paddy',
    variety: 'Katarni',
    gate_pass_no: 'Not Available',
    vehicle_no: 'AF 85812',
    weight_slip_no: 'Not Available',
    gross_weight_mt: null,
    tare_weight_mt: null,
    no_of_bags: 130,
    net_weight_mt: 5.420,
    rate_per_mt: 24050.00,
    gross_amount: 130351.00,
    hlw_wheat: null,
    excess_hlw: 0,
    deduction_amount_hlw: 0,
    moisture_moi: 15.50,
    excess_moisture: 1.50,
    bddi: null,
    excess_bddi: 0,
    moi_bddi: 1.50,
    weight_deduction_kg: 81.30,
    deduction_amount_moi_bddi: 1955.27,
    other_deductions: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    net_amount: 128395.73,
    remarks: ''
  },
  {
    transaction_date: '2024-12-15',
    state: 'Bihar',
    supplier_name: 'RUDRA ENTERPRISES',
    location: 'GULABBAGH',
    warehouse_name: 'SATISH KUMAR WAREHOUSE',
    chamber_no: '16',
    commodity: 'Paddy',
    variety: 'Katarni',
    gate_pass_no: 'Not Available',
    vehicle_no: 'AF 85813',
    weight_slip_no: 'Not Available',
    gross_weight_mt: null,
    tare_weight_mt: null,
    no_of_bags: 127,
    net_weight_mt: 5.330,
    rate_per_mt: 24050.00,
    gross_amount: 128186.50,
    hlw_wheat: null,
    excess_hlw: 0,
    deduction_amount_hlw: 0,
    moisture_moi: 15.30,
    excess_moisture: 1.30,
    bddi: null,
    excess_bddi: 0,
    moi_bddi: 1.30,
    weight_deduction_kg: 69.29,
    deduction_amount_moi_bddi: 1666.42,
    other_deductions: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    net_amount: 126520.08,
    remarks: ''
  },
  {
    transaction_date: '2024-12-15',
    state: 'Bihar',
    supplier_name: 'RUDRA ENTERPRISES',
    location: 'GULABBAGH',
    warehouse_name: 'SATISH KUMAR WAREHOUSE',
    chamber_no: '16',
    commodity: 'Paddy',
    variety: 'Katarni',
    gate_pass_no: 'Not Available',
    vehicle_no: 'AF 85814',
    weight_slip_no: 'Not Available',
    gross_weight_mt: null,
    tare_weight_mt: null,
    no_of_bags: 131,
    net_weight_mt: 5.450,
    rate_per_mt: 24050.00,
    gross_amount: 131072.50,
    hlw_wheat: null,
    excess_hlw: 0,
    deduction_amount_hlw: 0,
    moisture_moi: 15.70,
    excess_moisture: 1.70,
    bddi: null,
    excess_bddi: 0,
    moi_bddi: 1.70,
    weight_deduction_kg: 92.65,
    deduction_amount_moi_bddi: 2228.23,
    other_deductions: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    net_amount: 128844.27,
    remarks: ''
  },
  {
    transaction_date: '2024-12-15',
    state: 'Bihar',
    supplier_name: 'RUDRA ENTERPRISES',
    location: 'GULABBAGH',
    warehouse_name: 'SATISH KUMAR WAREHOUSE',
    chamber_no: '16',
    commodity: 'Paddy',
    variety: 'Katarni',
    gate_pass_no: 'Not Available',
    vehicle_no: 'AF 85815',
    weight_slip_no: 'Not Available',
    gross_weight_mt: null,
    tare_weight_mt: null,
    no_of_bags: 126,
    net_weight_mt: 5.280,
    rate_per_mt: 24050.00,
    gross_amount: 126984.00,
    hlw_wheat: null,
    excess_hlw: 0,
    deduction_amount_hlw: 0,
    moisture_moi: 15.20,
    excess_moisture: 1.20,
    bddi: null,
    excess_bddi: 0,
    moi_bddi: 1.20,
    weight_deduction_kg: 63.36,
    deduction_amount_moi_bddi: 1523.81,
    other_deductions: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    net_amount: 125460.19,
    remarks: ''
  },
  {
    transaction_date: '2024-12-15',
    state: 'Bihar',
    supplier_name: 'RUDRA ENTERPRISES',
    location: 'GULABBAGH',
    warehouse_name: 'SATISH KUMAR WAREHOUSE',
    chamber_no: '16',
    commodity: 'Paddy',
    variety: 'Katarni',
    gate_pass_no: 'Not Available',
    vehicle_no: 'AF 85816',
    weight_slip_no: 'Not Available',
    gross_weight_mt: null,
    tare_weight_mt: null,
    no_of_bags: 132,
    net_weight_mt: 5.480,
    rate_per_mt: 24050.00,
    gross_amount: 131794.00,
    hlw_wheat: null,
    excess_hlw: 0,
    deduction_amount_hlw: 0,
    moisture_moi: 15.80,
    excess_moisture: 1.80,
    bddi: null,
    excess_bddi: 0,
    moi_bddi: 1.80,
    weight_deduction_kg: 98.64,
    deduction_amount_moi_bddi: 2372.29,
    other_deductions: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    net_amount: 129421.71,
    remarks: ''
  }
];

async function importData() {
  try {
    // Connect to MongoDB
    await mongoose.connect(process.env.MONGODB_URI || 'mongodb://localhost:27017/grainology');
    console.log('✅ Connected to MongoDB');

    // Clear existing data (optional - remove if you want to keep existing)
    const existingCount = await SupplyTransaction.countDocuments();
    if (existingCount > 0) {
      console.log(`⚠️  Found ${existingCount} existing transactions`);
      console.log('ℹ️  Keeping existing data. New transactions will be added.');
    }

    // Insert data
    const result = await SupplyTransaction.insertMany(excelData, { ordered: false });
    console.log(`✅ Successfully imported ${result.length} transactions`);

    // Summary
    const totalAmount = result.reduce((sum, t) => sum + (t.net_amount || 0), 0);
    const totalWeight = result.reduce((sum, t) => sum + (t.net_weight_mt || 0), 0);
    
    console.log('\n📊 Import Summary:');
    console.log(`   Total Transactions: ${result.length}`);
    console.log(`   Total Net Amount: ₹${totalAmount.toLocaleString('en-IN', { maximumFractionDigits: 2 })}`);
    console.log(`   Total Net Weight: ${totalWeight.toFixed(2)} MT`);
    
    // Group by commodity
    const byCommodity = {};
    result.forEach(t => {
      byCommodity[t.commodity] = (byCommodity[t.commodity] || 0) + 1;
    });
    console.log('\n📦 By Commodity:');
    Object.entries(byCommodity).forEach(([commodity, count]) => {
      console.log(`   ${commodity}: ${count} transactions`);
    });

    process.exit(0);
  } catch (error) {
    console.error('❌ Error importing data:', error);
    process.exit(1);
  }
}

importData();
